language: node_js
sudo: required
cache: false
dist: trusty
os:
  - linux
node_js:
  - "13.8.0"

services:
  - xvfb
  - docker

addons:
  chrome: stable
  firefox: latest

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

stages:
  - implementations
  - examples

jobs:
  include:
    - stage: implementations
      script: (cd ./javascript && npm install > "/dev/null" 2>&1 &&  npm run lint && npm run build && travis_retry npm run test)
      env: LABEL=javascript

    - stage: examples
      script: (cd ./examples/browser && npm install > "/dev/null" 2>&1 &&  npm run lint && npm run build)
      env: LABEL=browser